IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='UserProfiles' AND xtype='U')
CREATE TABLE UserProfiles (
    ProfileId INT PRIMARY KEY,
    Email NVARCHAR(255),
    FirstName NVARCHAR(255),
    LastName NVARCHAR(255),
    IsManager BIT,
    IsHideReferralIOSBanner BIT,
    MarkerIcon NVARCHAR(255),
    Manager NVARCHAR(MAX),
    CRMEditableFieldsList NVARCHAR(MAX),
    CRMBaseUrl NVARCHAR(MAX),
    CRMType NVARCHAR(255),
    ReferralURL NVARCHAR(MAX),
    MapStartZoom INT,
    MapStart NVARCHAR(255),
    IsUserCanEdit BIT,
    IsUserCanDeleteCheckins BIT,
    IsUserCanAddNewTextValues BIT,
    HasData BIT,
    DefaultApptLength INT,
    Completed BIT,
    TrialDaysLeft INT,
    CompanyId INT,
    CompanyName NVARCHAR(255),
    CompanyShortName NVARCHAR(255),
    CreatedAt DATETIME2 DEFAULT GETDATE(),
    UpdatedAt DATETIME2 DEFAULT GETDATE()
); 