MERGE [Accounts] AS target
USING (SELECT ? as Id, ? as FirstName, ? as LastName, ? as FullName, 
       ? as PhoneNumber, ? as Email, ? as AccountOwner, ? as CustomerId, ? as Notes, 
       ? as OriginalAddress, ? as CrmId, ? as DaysSinceLastCheckin, ? as FollowUpDate,
       ? as LastCheckinDate, ? as LastModifiedDate,
       ? as CustomNumeric, ? as CustomText, ? as CustomNumeric2, ? as CustomText2,
       ? as CustomNumeric3, ? as CustomText3, ? as CustomNumeric4, ? as CustomText4,
       ? as CustomNumeric5, ? as CustomText5, ? as CustomNumeric6, ? as CustomText6,
       ? as CustomNumeric7, ? as CustomText7, ? as CustomNumeric8, ? as CustomText8,
       ? as CustomNumeric9, ? as CustomText9, ? as CustomNumeric10, ? as CustomText10,
       ? as CustomNumeric11, ? as CustomText11, ? as CustomNumeric12, ? as CustomText12,
       ? as CustomNumeric13, ? as CustomText13, ? as CustomNumeric14, ? as CustomText14,
       ? as CustomNumeric15, ? as CustomText15, ? as CustomNumeric16, ? as CustomText16,
       ? as CustomNumeric17, ? as CustomText17, ? as CustomNumeric18, ? as CustomText18,
       ? as CustomNumeric19, ? as CustomText19, ? as CustomNumeric20, ? as CustomText20,
       ? as CustomNumeric21, ? as CustomText21, ? as CustomNumeric22, ? as CustomText22,
       ? as CustomNumeric23, ? as CustomText23, ? as CustomNumeric24, ? as CustomText24,
       ? as CustomNumeric25, ? as CustomText25, ? as CustomNumeric26, ? as CustomText26,
       ? as CustomNumeric27, ? as CustomText27, ? as CustomNumeric28, ? as CustomText28,
       ? as CustomNumeric29, ? as CustomText29, ? as CustomNumeric30, ? as CustomText30) AS source
ON target.[Id] = source.Id
WHEN MATCHED THEN
	UPDATE SET 
		[FirstName] = source.FirstName,
		[LastName] = source.LastName,
		[FullName] = source.FullName,
		[PhoneNumber] = source.PhoneNumber,
		[Email] = source.Email,
		[AccountOwner] = source.AccountOwner,
		[CustomerId] = source.CustomerId,
		[Notes] = source.Notes,
		[OriginalAddress] = source.OriginalAddress,
		[CrmId] = source.CrmId,
		[DaysSinceLastCheckin] = source.DaysSinceLastCheckin,
		[FollowUpDate] = source.FollowUpDate,
		[LastCheckinDate] = source.LastCheckinDate,
		[LastModifiedDate] = source.LastModifiedDate,
		[CustomNumeric] = source.CustomNumeric,
		[CustomText] = source.CustomText,
		[CustomNumeric2] = source.CustomNumeric2,
		[CustomText2] = source.CustomText2,
		[CustomNumeric3] = source.CustomNumeric3,
		[CustomText3] = source.CustomText3,
		[CustomNumeric4] = source.CustomNumeric4,
		[CustomText4] = source.CustomText4,
		[CustomNumeric5] = source.CustomNumeric5,
		[CustomText5] = source.CustomText5,
		[CustomNumeric6] = source.CustomNumeric6,
		[CustomText6] = source.CustomText6,
		[CustomNumeric7] = source.CustomNumeric7,
		[CustomText7] = source.CustomText7,
		[CustomNumeric8] = source.CustomNumeric8,
		[CustomText8] = source.CustomText8,
		[CustomNumeric9] = source.CustomNumeric9,
		[CustomText9] = source.CustomText9,
		[CustomNumeric10] = source.CustomNumeric10,
		[CustomText10] = source.CustomText10,
		[CustomNumeric11] = source.CustomNumeric11,
		[CustomText11] = source.CustomText11,
		[CustomNumeric12] = source.CustomNumeric12,
		[CustomText12] = source.CustomText12,
		[CustomNumeric13] = source.CustomNumeric13,
		[CustomText13] = source.CustomText13,
		[CustomNumeric14] = source.CustomNumeric14,
		[CustomText14] = source.CustomText14,
		[CustomNumeric15] = source.CustomNumeric15,
		[CustomText15] = source.CustomText15,
		[CustomNumeric16] = source.CustomNumeric16,
		[CustomText16] = source.CustomText16,
		[CustomNumeric17] = source.CustomNumeric17,
		[CustomText17] = source.CustomText17,
		[CustomNumeric18] = source.CustomNumeric18,
		[CustomText18] = source.CustomText18,
		[CustomNumeric19] = source.CustomNumeric19,
		[CustomText19] = source.CustomText19,
		[CustomNumeric20] = source.CustomNumeric20,
		[CustomText20] = source.CustomText20,
		[CustomNumeric21] = source.CustomNumeric21,
		[CustomText21] = source.CustomText21,
		[CustomNumeric22] = source.CustomText22,
		[CustomText22] = source.CustomText22,
		[CustomNumeric23] = source.CustomNumeric23,
		[CustomText23] = source.CustomText23,
		[CustomNumeric24] = source.CustomNumeric24,
		[CustomText24] = source.CustomText24,
		[CustomNumeric25] = source.CustomNumeric25,
		[CustomText25] = source.CustomText25,
		[CustomNumeric26] = source.CustomNumeric26,
		[CustomText26] = source.CustomText26,
		[CustomNumeric27] = source.CustomNumeric27,
		[CustomText27] = source.CustomText27,
		[CustomNumeric28] = source.CustomNumeric28,
		[CustomText28] = source.CustomText28,
		[CustomNumeric29] = source.CustomNumeric29,
		[CustomText29] = source.CustomText29,
		[CustomNumeric30] = source.CustomNumeric30,
		[CustomText30] = source.CustomText30,
		[UpdatedAt] = GETDATE()
WHEN NOT MATCHED THEN
	INSERT ([Id], [FirstName], [LastName], [FullName], [PhoneNumber], [Email], [AccountOwner], 
	        [CustomerId], [Notes], [OriginalAddress], [CrmId], [DaysSinceLastCheckin], [FollowUpDate],
	        [LastCheckinDate], [LastModifiedDate], [CustomNumeric], [CustomText], [CustomNumeric2], 
	        [CustomText2], [CustomNumeric3], [CustomText3], [CustomNumeric4], [CustomText4], 
	        [CustomNumeric5], [CustomText5], [CustomNumeric6], [CustomText6], [CustomNumeric7], 
	        [CustomText7], [CustomNumeric8], [CustomText8], [CustomNumeric9], [CustomText9], 
	        [CustomNumeric10], [CustomText10], [CustomNumeric11], [CustomText11], [CustomNumeric12], 
	        [CustomText12], [CustomNumeric13], [CustomText13], [CustomNumeric14], [CustomText14], 
	        [CustomNumeric15], [CustomText15], [CustomNumeric16], [CustomText16], [CustomNumeric17], 
	        [CustomText17], [CustomNumeric18], [CustomText18], [CustomNumeric19], [CustomText19], 
	        [CustomNumeric20], [CustomText20], [CustomNumeric21], [CustomText21], [CustomNumeric22], 
	        [CustomText22], [CustomNumeric23], [CustomText23], [CustomNumeric24], [CustomText24], 
	        [CustomNumeric25], [CustomText25], [CustomNumeric26], [CustomText26], [CustomNumeric27], 
	        [CustomText27], [CustomNumeric28], [CustomText28], [CustomNumeric29], [CustomText29], 
	        [CustomNumeric30], [CustomText30])
	VALUES (source.Id, source.FirstName, source.LastName, source.FullName, source.PhoneNumber, 
	        source.Email, source.AccountOwner, source.CustomerId, source.Notes, source.OriginalAddress, 
	        source.CrmId, source.DaysSinceLastCheckin, source.FollowUpDate, source.LastCheckinDate, 
	        source.LastModifiedDate, source.CustomNumeric, source.CustomText, source.CustomNumeric2, 
	        source.CustomText2, source.CustomNumeric3, source.CustomText3, source.CustomNumeric4, 
	        source.CustomText4, source.CustomNumeric5, source.CustomText5, source.CustomNumeric6, 
	        source.CustomText6, source.CustomNumeric7, source.CustomText7, source.CustomNumeric8, 
	        source.CustomText8, source.CustomNumeric9, source.CustomText9, source.CustomNumeric10, 
	        source.CustomText10, source.CustomNumeric11, source.CustomText11, source.CustomNumeric12, 
	        source.CustomText12, source.CustomNumeric13, source.CustomText13, source.CustomNumeric14, 
	        source.CustomText14, source.CustomNumeric15, source.CustomText15, source.CustomNumeric16, 
	        source.CustomText16, source.CustomNumeric17, source.CustomText17, source.CustomNumeric18, 
	        source.CustomText18, source.CustomNumeric19, source.CustomText19, source.CustomNumeric20, 
	        source.CustomText20, source.CustomNumeric21, source.CustomText21, source.CustomNumeric22, 
	        source.CustomText22, source.CustomNumeric23, source.CustomText23, source.CustomNumeric24, 
	        source.CustomText24, source.CustomNumeric25, source.CustomText25, source.CustomNumeric26, 
	        source.CustomText26, source.CustomNumeric27, source.CustomText27, source.CustomNumeric28, 
	        source.CustomText28, source.CustomNumeric29, source.CustomText29, source.CustomNumeric30, 
	        source.CustomText30); 