CREATE TABLE IF NOT EXISTS WebhookLog (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    ReceivedAt DATETIME NOT NULL,
    Method TEXT NOT NULL,
    Uri TEXT NOT NULL,
    Headers TEXT,
    Body TEXT
);
