CREATE TABLE IF NOT EXISTS DataSetValues (
    Id INTEGER PRIMARY KEY,
    ProfileId INTEGER,
    DataSetId INTEGER,
    DataSetName TEXT,
    DataSetPosition INTEGER,
    Text TEXT,
    Value TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);