CREATE TABLE IF NOT EXISTS CommandLog (
    LogId INTEGER PRIMARY KEY AUTOINCREMENT,
    Command TEXT NOT NULL,
    Args TEXT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    Success BOOLEAN NOT NULL,
    ErrorMessage TEXT
);
