CREATE TABLE IF NOT EXISTS DataSets (
    Id INTEGER PRIMARY KEY,
    Name TEXT,
    Description TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);