CREATE TABLE IF NOT EXISTS UserProfiles (
    ProfileId INTEGER PRIMARY KEY,
    Email TEXT,
    FirstName TEXT,
    LastName TEXT,
    IsManager BOOLEAN,
    IsHideReferralIOSBanner BOOLEAN,
    MarkerIcon TEXT,
    Manager TEXT,
    CRMEditableFieldsList TEXT,
    CRMBaseUrl TEXT,
    CRMType TEXT,
    ReferralURL TEXT,
    MapStartZoom INTEGER,
    MapStart TEXT,
    IsUserCanEdit BOOLEAN,
    IsUserCanDeleteCheckins BOOLEAN,
    IsUserCanAddNewTextValues BOOLEAN,
    HasData BOOLEAN,
    DefaultApptLength INTEGER,
    Completed BOOLEAN,
    TrialDaysLeft INTEGER,
    CompanyId INTEGER,
    CompanyName TEXT,
    CompanyShortName TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);