CREATE TABLE IF NOT EXISTS DataSetValues (
    Id INTEGER PRIMARY KEY,
    DataSetId INTEGER,
    Value TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);