CREATE TABLE IF NOT EXISTS RouteWaypoints (
    WaypointId INTEGER PRIMARY KEY,
    RouteId INTEGER,
    Name TEXT,
    Address TEXT,
    Suite TEXT,
    City TEXT,
    State TEXT,
    Zipcode TEXT,
    Location TEXT,
    Latitude REAL,
    Longitude REAL,
    LayoverMinutes INTEGER,
    Position INTEGER,
    CompleteAddress TEXT,
    LocationId INTEGER,
    CustomerId INTEGER,
    ApptTime DATETIME,
    Type INTEGER,
    PlaceId TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);