CREATE TABLE IF NOT EXISTS JobLog (
    HistoryId INTEGER PRIMARY KEY AUTOINCREMENT,
    CorrelationId TEXT NOT NULL UNIQUE,
    ParentCorrelationId TEXT,
    RootCorrelationId TEXT,
    RunType TEXT NOT NULL,
    Direction TEXT NOT NULL,
    Source TEXT,
    Initiator TEXT,
    JobKind TEXT,
    Mode TEXT,
    StepId TEXT,
    StepIndex INTEGER DEFAULT 0,
    TotalSteps INTEGER DEFAULT 0,
    ActionType TEXT,
    CommandText TEXT,
    Status TEXT NOT NULL,
    ItemsProcessed INTEGER DEFAULT 0,
    ErrorCount INTEGER DEFAULT 0,
    StartedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    StartedAtTimezone TEXT NOT NULL DEFAULT 'UTC',
    CompletedAt DATETIME,
    CompletedAtTimezone TEXT,
    DurationSeconds INTEGER,
    Summary TEXT,
    Details TEXT
);
