CREATE TABLE IF NOT EXISTS Accounts (
    Id SERIAL PRIMARY KEY,
    FirstName VARCHAR(255),
    LastName VARCHAR(255),
    PhoneNumber VARCHAR(50),
    Email VARCHAR(255),
    CustomerId VARCHAR(255),
    Notes TEXT,
    OriginalAddress TEXT,
    CrmId VARCHAR(255),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);