CREATE TABLE IF NOT EXISTS JobLog (
    HistoryId SERIAL PRIMARY KEY,
    CorrelationId VARCHAR(128) NOT NULL UNIQUE,
    ParentCorrelationId VARCHAR(128),
    RootCorrelationId VARCHAR(128),
    RunType VARCHAR(40) NOT NULL,
    Direction VARCHAR(40) NOT NULL,
    Source VARCHAR(80),
    Initiator VARCHAR(40),
    JobKind VARCHAR(40),
    Mode VARCHAR(40),
    StepId VARCHAR(128),
    StepIndex INTEGER DEFAULT 0,
    TotalSteps INTEGER DEFAULT 0,
    ActionType VARCHAR(40),
    CommandText TEXT,
    Status VARCHAR(40) NOT NULL,
    ItemsProcessed INTEGER DEFAULT 0,
    ErrorCount INTEGER DEFAULT 0,
    StartedAt TIMESTAMP DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    StartedAtTimezone VARCHAR(128) NOT NULL DEFAULT 'UTC',
    CompletedAt TIMESTAMP,
    CompletedAtTimezone VARCHAR(128),
    DurationSeconds INTEGER,
    Summary TEXT,
    Details TEXT
);
