CREATE TABLE IF NOT EXISTS UserProfiles (
    Id SERIAL PRIMARY KEY,
    Email VARCHAR(255),
    FirstName VARCHAR(255),
    LastName VARCHAR(255),
    IsManager BOOLEAN,
    CrmBaseUrl TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);