CREATE TABLE IF NOT EXISTS data_set_values (
    id SERIAL PRIMARY KEY,
    data_set_id INTEGER,
    value TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);