CREATE TABLE IF NOT EXISTS RouteWaypoints (
    WaypointId SERIAL PRIMARY KEY,
    RouteId INTEGER,
    Name VARCHAR(255),
    Address TEXT,
    Suite TEXT,
    City TEXT,
    State TEXT,
    Zipcode TEXT,
    Location TEXT,
    Latitude DECIMAL(10, 8),
    Longitude DECIMAL(11, 8),
    LayoverMinutes INTEGER,
    Position INTEGER,
    CompleteAddress TEXT,
    LocationId INTEGER,
    CustomerId INTEGER,
    ApptTime TIMESTAMP,
    Type INTEGER,
    PlaceId TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);