CREATE TABLE IF NOT EXISTS DataSetValues (
    DataSetValueId SERIAL PRIMARY KEY,
    ProfileId INTEGER,
    DataSetName TEXT,
    DataSetPosition INTEGER,
    Text TEXT,
    Value TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);