CREATE TABLE IF NOT EXISTS DataSetValues (
    ProfileId INTEGER,
    DataSetId INTEGER,
    DataSetName TEXT,
    DataSetPosition INTEGER,
    Text TEXT,
    Value TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);