CREATE OR REPLACE FUNCTION RefreshFieldMaps()
RETURNS TRIGGER AS $
BEGIN
    PERFORM UpdateFieldMapsFromDatasets();
    RETURN NULL;
END;
$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS DatasetsFieldMapsUpdateTrigger ON "DataSets";

CREATE TRIGGER DatasetsFieldMapsUpdateTrigger
AFTER INSERT OR UPDATE OR DELETE ON "DataSets"
FOR EACH STATEMENT
EXECUTE FUNCTION RefreshFieldMaps();
