CREATE TABLE IF NOT EXISTS DataSets (
    Id SERIAL PRIMARY KEY,
    Name VARCHAR(255),
    Description TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);