CREATE TABLE IF NOT EXISTS CommandLog (
    LogId SERIAL PRIMARY KEY,
    Command TEXT NOT NULL,
    Args TEXT,
    Timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    Success BOOLEAN NOT NULL,
    ErrorMessage TEXT
);
