CREATE TABLE IF NOT EXISTS UserProfiles (
    ProfileId INT PRIMARY KEY,
    Email VARCHAR(255),
    FirstName VARCHAR(255),
    LastName VARCHAR(255),
    IsManager BOOLEAN,
    IsHideReferralIOSBanner BOOLEAN,
    MarkerIcon VARCHAR(255),
    Manager TEXT,
    CRMEditableFieldsList TEXT,
    CRMBaseUrl TEXT,
    CRMType VARCHAR(255),
    ReferralURL TEXT,
    MapStartZoom INT,
    MapStart VARCHAR(255),
    IsUserCanEdit BOOLEAN,
    IsUserCanDeleteCheckins BOOLEAN,
    IsUserCanAddNewTextValues BOOLEAN,
    HasData BOOLEAN,
    DefaultApptLength INT,
    Completed BOOLEAN,
    TrialDaysLeft INT,
    CompanyId INT,
    CompanyName VARCHAR(255),
    CompanyShortName VARCHAR(255),
    CreatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);