INSERT INTO Accounts (
    AccountId,
    FirstName,
    LastName,
    FullName,
    PhoneNumber,
    Email,
    AccountOwner,
    CustomerId,
    Notes,
    OriginalAddress,
    CrmId,
    DaysSinceLastCheckin,
    FollowUpDate,
    LastCheckinDate,
    LastModifiedDate,
    CustomNumeric,
    CustomText,
    CustomNumeric2,
    CustomText2,
    CustomNumeric3,
    CustomText3,
    CustomNumeric4,
    CustomText4,
    CustomNumeric5,
    CustomText5,
    CustomNumeric6,
    CustomText6,
    CustomNumeric7,
    CustomText7,
    CustomNumeric8,
    CustomText8,
    CustomNumeric9,
    CustomText9,
    CustomNumeric10,
    CustomText10,
    CustomNumeric11,
    CustomText11,
    CustomNumeric12,
    CustomText12,
    CustomNumeric13,
    CustomText13,
    CustomNumeric14,
    CustomText14,
    CustomNumeric15,
    CustomText15,
    CustomNumeric16,
    CustomText16,
    CustomNumeric17,
    CustomText17,
    CustomNumeric18,
    CustomText18,
    CustomNumeric19,
    CustomText19,
    CustomNumeric20,
    CustomText20,
    CustomNumeric21,
    CustomText21,
    CustomNumeric22,
    CustomText22,
    CustomNumeric23,
    CustomText23,
    CustomNumeric24,
    CustomText24,
    CustomNumeric25,
    CustomText25,
    CustomNumeric26,
    CustomText26,
    CustomNumeric27,
    CustomText27,
    CustomNumeric28,
    CustomText28,
    CustomNumeric29,
    CustomText29,
    CustomNumeric30,
    CustomText30,
    CreatedAt,
    UpdatedAt
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32,
    $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47,
    $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61, $62,
    $63, $64, $65, $66, $67, $68, $69, $70, $71, $72, $73, $74, $75, $76, $77
)
ON CONFLICT (AccountId) DO UPDATE SET
    FirstName = EXCLUDED.FirstName,
    LastName = EXCLUDED.LastName,
    FullName = EXCLUDED.FullName,
    PhoneNumber = EXCLUDED.PhoneNumber,
    Email = EXCLUDED.Email,
    AccountOwner = EXCLUDED.AccountOwner,
    CustomerId = EXCLUDED.CustomerId,
    Notes = EXCLUDED.Notes,
    OriginalAddress = EXCLUDED.OriginalAddress,
    CrmId = EXCLUDED.CrmId,
    DaysSinceLastCheckin = EXCLUDED.DaysSinceLastCheckin,
    FollowUpDate = EXCLUDED.FollowUpDate,
    LastCheckinDate = EXCLUDED.LastCheckinDate,
    LastModifiedDate = EXCLUDED.LastModifiedDate,
    CustomNumeric = EXCLUDED.CustomNumeric,
    CustomText = EXCLUDED.CustomText,
    CustomNumeric2 = EXCLUDED.CustomNumeric2,
    CustomText2 = EXCLUDED.CustomText2,
    CustomNumeric3 = EXCLUDED.CustomNumeric3,
    CustomText3 = EXCLUDED.CustomText3,
    CustomNumeric4 = EXCLUDED.CustomNumeric4,
    CustomText4 = EXCLUDED.CustomText4,
    CustomNumeric5 = EXCLUDED.CustomNumeric5,
    CustomText5 = EXCLUDED.CustomText5,
    CustomNumeric6 = EXCLUDED.CustomNumeric6,
    CustomText6 = EXCLUDED.CustomText6,
    CustomNumeric7 = EXCLUDED.CustomNumeric7,
    CustomText7 = EXCLUDED.CustomText7,
    CustomNumeric8 = EXCLUDED.CustomNumeric8,
    CustomText8 = EXCLUDED.CustomText8,
    CustomNumeric9 = EXCLUDED.CustomNumeric9,
    CustomText9 = EXCLUDED.CustomText9,
    CustomNumeric10 = EXCLUDED.CustomNumeric10,
    CustomText10 = EXCLUDED.CustomText10,
    CustomNumeric11 = EXCLUDED.CustomNumeric11,
    CustomText11 = EXCLUDED.CustomText11,
    CustomNumeric12 = EXCLUDED.CustomNumeric12,
    CustomText12 = EXCLUDED.CustomText12,
    CustomNumeric13 = EXCLUDED.CustomNumeric13,
    CustomText13 = EXCLUDED.CustomText13,
    CustomNumeric14 = EXCLUDED.CustomNumeric14,
    CustomText14 = EXCLUDED.CustomText14,
    CustomNumeric15 = EXCLUDED.CustomNumeric15,
    CustomText15 = EXCLUDED.CustomText15,
    CustomNumeric16 = EXCLUDED.CustomNumeric16,
    CustomText16 = EXCLUDED.CustomText16,
    CustomNumeric17 = EXCLUDED.CustomNumeric17,
    CustomText17 = EXCLUDED.CustomText17,
    CustomNumeric18 = EXCLUDED.CustomNumeric18,
    CustomText18 = EXCLUDED.CustomText18,
    CustomNumeric19 = EXCLUDED.CustomNumeric19,
    CustomText19 = EXCLUDED.CustomText19,
    CustomNumeric20 = EXCLUDED.CustomNumeric20,
    CustomText20 = EXCLUDED.CustomText20,
    CustomNumeric21 = EXCLUDED.CustomNumeric21,
    CustomText21 = EXCLUDED.CustomText21,
    CustomNumeric22 = EXCLUDED.CustomNumeric22,
    CustomText22 = EXCLUDED.CustomText22,
    CustomNumeric23 = EXCLUDED.CustomNumeric23,
    CustomText23 = EXCLUDED.CustomText23,
    CustomNumeric24 = EXCLUDED.CustomNumeric24,
    CustomText24 = EXCLUDED.CustomText24,
    CustomNumeric25 = EXCLUDED.CustomNumeric25,
    CustomText25 = EXCLUDED.CustomText25,
    CustomNumeric26 = EXCLUDED.CustomNumeric26,
    CustomText26 = EXCLUDED.CustomText26,
    CustomNumeric27 = EXCLUDED.CustomNumeric27,
    CustomText27 = EXCLUDED.CustomText27,
    CustomNumeric28 = EXCLUDED.CustomNumeric28,
    CustomText28 = EXCLUDED.CustomText28,
    CustomNumeric29 = EXCLUDED.CustomNumeric29,
    CustomText29 = EXCLUDED.CustomText29,
    CustomNumeric30 = EXCLUDED.CustomNumeric30,
    CustomText30 = EXCLUDED.CustomText30,
    UpdatedAt = EXCLUDED.UpdatedAt;